// <auto-generated />
using Bagels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bagels.Migrations
{
    [DbContext(typeof(BagelsContext))]
    [Migration("20191030172709_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bagels.Models.Bagel", b =>
                {
                    b.Property<int>("BagelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Flavor");

                    b.Property<string>("SuggestedToppings");

                    b.HasKey("BagelId");

                    b.ToTable("Bagels");

                    b.HasData(
                        new
                        {
                            BagelId = 1,
                            Flavor = "Plain",
                            SuggestedToppings = "Butter"
                        },
                        new
                        {
                            BagelId = 2,
                            Flavor = "Sesame",
                            SuggestedToppings = "Cream cheese, tomato, onion"
                        },
                        new
                        {
                            BagelId = 3,
                            Flavor = "Asiago",
                            SuggestedToppings = "Cream cheese, cheddar cheese, and parmesan cheese"
                        },
                        new
                        {
                            BagelId = 4,
                            Flavor = "Salt",
                            SuggestedToppings = "Extra cream cheese"
                        },
                        new
                        {
                            BagelId = 5,
                            Flavor = "Everything",
                            SuggestedToppings = "Hummus, avocado, sprouts"
                        });
                });

            modelBuilder.Entity("Bagels.Models.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ToppingId");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            ToppingId = 1,
                            Name = "Cream Cheese"
                        },
                        new
                        {
                            ToppingId = 2,
                            Name = "Slice of Pizza"
                        },
                        new
                        {
                            ToppingId = 3,
                            Name = "Salmon (whole fish)"
                        },
                        new
                        {
                            ToppingId = 4,
                            Name = "Butter"
                        },
                        new
                        {
                            ToppingId = 5,
                            Name = "Avocado"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
