// <auto-generated />
using Bagels.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bagels.Migrations
{
    [DbContext(typeof(BagelsContext))]
    [Migration("20191030181011_MoreSeedData")]
    partial class MoreSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Bagels.Models.Bagel", b =>
                {
                    b.Property<int>("BagelId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Flavor");

                    b.Property<string>("SuggestedToppings");

                    b.HasKey("BagelId");

                    b.ToTable("Bagels");

                    b.HasData(
                        new
                        {
                            BagelId = 1,
                            Flavor = "Plain",
                            SuggestedToppings = "Butter"
                        },
                        new
                        {
                            BagelId = 2,
                            Flavor = "Sesame",
                            SuggestedToppings = "Cream cheese, tomato, onion"
                        },
                        new
                        {
                            BagelId = 3,
                            Flavor = "Asiago",
                            SuggestedToppings = "Cream cheese, cheddar cheese, and parmesan cheese"
                        },
                        new
                        {
                            BagelId = 4,
                            Flavor = "Salt",
                            SuggestedToppings = "Extra cream cheese"
                        },
                        new
                        {
                            BagelId = 5,
                            Flavor = "Everything",
                            SuggestedToppings = "Hummus, avocado, sprouts"
                        },
                        new
                        {
                            BagelId = 6,
                            Flavor = "Pumpernickle",
                            SuggestedToppings = "Cream cheese, lox, capers, onion"
                        },
                        new
                        {
                            BagelId = 7,
                            Flavor = "Poppy Seed",
                            SuggestedToppings = "Avocado, tomato, salt, capers"
                        },
                        new
                        {
                            BagelId = 8,
                            Flavor = "Bialy",
                            SuggestedToppings = "Cream cheese, butter, salt, pepper"
                        },
                        new
                        {
                            BagelId = 9,
                            Flavor = "Multigrain",
                            SuggestedToppings = "Butter, cinnamon-sugar"
                        },
                        new
                        {
                            BagelId = 10,
                            Flavor = "Whole Wheat",
                            SuggestedToppings = "Extra avocado, cream cheese"
                        },
                        new
                        {
                            BagelId = 11,
                            Flavor = "Jalapeno",
                            SuggestedToppings = "Cheddar cheese, hummus, pickled jalapenos"
                        },
                        new
                        {
                            BagelId = 12,
                            Flavor = "Cinnamon Raisin",
                            SuggestedToppings = "Cream Cheese, extra raisins"
                        },
                        new
                        {
                            BagelId = 13,
                            Flavor = "Onion",
                            SuggestedToppings = "Cream cheese, whole salmon"
                        },
                        new
                        {
                            BagelId = 14,
                            Flavor = "Garlic",
                            SuggestedToppings = "Mayonnaise"
                        },
                        new
                        {
                            BagelId = 15,
                            Flavor = "Chocolate Chip",
                            SuggestedToppings = "Nothing, just plain"
                        },
                        new
                        {
                            BagelId = 16,
                            Flavor = "Egg",
                            SuggestedToppings = "Scambled egg, cheddar, bacon"
                        },
                        new
                        {
                            BagelId = 17,
                            Flavor = "Gluten-free Bagel",
                            SuggestedToppings = "Spinach, lowfat Cream Cheese, avocado"
                        });
                });

            modelBuilder.Entity("Bagels.Models.Topping", b =>
                {
                    b.Property<int>("ToppingId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("ToppingId");

                    b.ToTable("Toppings");

                    b.HasData(
                        new
                        {
                            ToppingId = 1,
                            Name = "Cream Cheese"
                        },
                        new
                        {
                            ToppingId = 2,
                            Name = "Slice of Pizza"
                        },
                        new
                        {
                            ToppingId = 3,
                            Name = "Salmon (whole fish)"
                        },
                        new
                        {
                            ToppingId = 4,
                            Name = "Stick of Butter"
                        },
                        new
                        {
                            ToppingId = 5,
                            Name = "Avocado"
                        },
                        new
                        {
                            ToppingId = 6,
                            Name = "Burrito"
                        },
                        new
                        {
                            ToppingId = 7,
                            Name = "Sushi Rolls"
                        },
                        new
                        {
                            ToppingId = 8,
                            Name = "Noodles"
                        },
                        new
                        {
                            ToppingId = 9,
                            Name = "Tomato"
                        },
                        new
                        {
                            ToppingId = 10,
                            Name = "Sloppy Joes"
                        },
                        new
                        {
                            ToppingId = 11,
                            Name = "Pesto"
                        },
                        new
                        {
                            ToppingId = 12,
                            Name = "Lettuce"
                        },
                        new
                        {
                            ToppingId = 13,
                            Name = "Alfredo Sauce"
                        },
                        new
                        {
                            ToppingId = 14,
                            Name = "Bagel"
                        },
                        new
                        {
                            ToppingId = 15,
                            Name = "Grilled Cheese Sandwich"
                        },
                        new
                        {
                            ToppingId = 16,
                            Name = "Dumplings"
                        },
                        new
                        {
                            ToppingId = 17,
                            Name = "Pickled Jalapenos"
                        },
                        new
                        {
                            ToppingId = 18,
                            Name = "Cucumber"
                        },
                        new
                        {
                            ToppingId = 19,
                            Name = "Pickles"
                        },
                        new
                        {
                            ToppingId = 20,
                            Name = "Jasmine Rice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
